### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by dfreireu4** [dsone/remote-ssh#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-SSH](https://github.com/dsone/remote-ssh) package 0.8.1

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:549

TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:549:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:200:20)
    at Object.fs.writeFile (fs.js:1211:6)
    at /packages/Remote-SSH/node_modules/fs-plus/lib/fs-plus.js:300:21
    at /packages/Remote-SSH/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:09.6.0 remote-ssh:create-config (atom-pane.pane.active)
```

### Non-Core Packages

```
Remote-SSH 0.8.1 
ssh-config 0.12.0 
```

**Comment by dsone** [comment]
Seems to be linked to some odd behaviour of a node_module trying to access files and failing at it.
Can't reproduce it but had it once after creating a new project and never again.
Added more error handling, trying to catch this oddity before throwing an exception for now.
