### ISSUE TITLE
How use?

### ISSUE THREAD

**Issue by DimaCrafter** [dsone/remote-ssh#3]
I create and fill config and try start session but nothing happens

**Comment by dsone** [comment]
`{
    "protocol": "sftp",
    "port": 22,
    "host": "yourhost",
    "user": "youruser",
    "pass": "yourpassword"
}`
Your .ftpconfig should contain at least this information in your project folder. With remote-ssh installed and Putty globally accessible (i.e. Putty in your PATH variable) you can start Putty with the shortcut STRG+ALT+R.
Make sure the json is valid and Putty in your PATH.
Please keep in mind, remote-ssh is currently only working on Windows.
