### ISSUE TITLE
How to use remote-ssh ?

### ISSUE THREAD

**Issue by webmasterpf** [dsone/remote-ssh#5]
Hi,

I want to use Atom, and I need access to ssh connexion via a terminal. 
I have a session set in Putty so I create a .ftpconfig like this:

```
{
    "protocol": "ftp",
    "host": "10.100.3.90",
    "port": 21,
    "user": "XX",
    "pass": "XX",
    "promptForPass": false,
    "remote": "/drupal-8/themes/custom/starterpf_d8_2019",
    "local": "",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch": [],
    "watchTimeout": 500

    "protocol": "ssh",
    "host": "10.100.3.90",
    "port": 22,
    "user": "XX",
    "pass": "",

    "session": "VM DG Local 10.100.3.90 SSH - Webmaster",
    "rs_name": "",
    "rs_tags": []
}
```

But I get an error on the syntax file.
Then, do I need to use a terminal package  like terminalio ?
Thanks

**Comment by dsone** [comment]
You have a syntax error in your JSON. That's not an issue specific with Remote-SSH.
There's a comma missing in the line of watchTimeout. You also have repetition in your JSON (protocol, host, etc.).

Minimal example:
```JSON
{
    "protocol": "sftp",
    "host": "XX",
    "port": "22",
    "user": "XX",
    "pass": "XX",
    "promptForPass": false,
    "remote": "/",
    "local": "",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "remoteCommand": "",
    "remoteShell": "",
    "watch": [],
    "watchTimeout": 500,

    "session": "Dev Server XY",
    "rs_name": "My Super Awesome Project",
    "rs_tags": [ "super", "awesome", "project" ]
}
```
Whereas XX is your server and credentials.
Then simply hit CTRL+ALT+R for Remote-SSH to start Putty with a session named "Dev Server XY".
Or if you simply want to connect to the server entered in "host", you can remove the value inside session and simply hit CTRL+ALT+R. Remote-SSH will then use the entered user/pass for host.

Make sure Putty is globally accessible. Meaning, you can enter "putty" in a cmd console from wherever to start Putty.

**Comment by webmasterpf** [comment]
Thanks but I need to connect both FTP and SSH  simultaneously. How can I do that ? And is putty will open a terminal inside Atom instead of open it outside ? (like netbeans does)

**Comment by dsone** [comment]
Remote-SSH uses .ftpconfig specifically to work smoothly with Remote-FTP. 
Neither Remote-FTP nor Remote-SSH can simultaneously open two connections.
In addition duplicate keys inside JSON - while valid JSON - overwrite preceding values.
I am afraid your use-case exceeds the capabilities of JSON.

What you could do is create a new folder and put another .ftpconfig inside with your sftp/ssh credentials OR another session and name it rs_name: "My SFTP connection".
Then you can search for that rs_name via CTRL+ALT+S and open it.

Putty is an external program, so it opens detached from Atom in a new console window.

**Comment by webmasterpf** [comment]
So I will look after https://atom.io/packages/platformio-ide-terminal , but actually I can't connect SSH via cmd or powershell..W10 is weird. ;) Because the goal is to have an eye on sass compilation with gulp.

**Comment by dsone** [comment]
Yes, SSH on Windows is a pain. That's why I created Remote-SSH to make that easier with automagically starting a Putty instance for the currently checkedout project folder. ;)
